d, e, z = map(int, input("введите числа").split())
one = d * e
two = e * z
tree = z * d
print ("умножить d на e =" , one)
print ("умножить e на z =" , two)
print ("умножить z на d =" , tree)
one2 = d ** 4
two2 = e % z
tree2 = z // d 
print ("Возвести в четвертую степень первое число =" , one2)
print ("узнать остаток от деления второго числа на третье =" , two2)
print ("целочисленное деление третьего числа на первое =" , tree2)
one3 = (d + e + z)
print ("сложить все числа =" , one3) 
